#include <stdio.h>
#include <stdlib.h>

/* FUNCIONES PARA EL MANEJO DE CARACTERES DE LA BIBLIOTECA STDLIB.H. */

void main(void)
{
    int i;
    double d;
    long l;
    char cad0[20], *cad1;

    printf("\nIngrese una cadena de caracteres: ");
    gets(cad0);
    i = atoi(cad0);
    /* LA FUNCION ATOI CONVIERTE UNA CADENA DE CARACTERES QUE CONTIENE NUMEROS
    A UN VALOR DE TIPO ENTERO. SI LA CADENA COMIENZA CON OTRO CARACTER O NO
    CONTIENE NUMEROS, RERESA 0 O EL VALOR QUEDA INDEFINIDO. */
    printf("\n%s \t%d", cad0, i+3);
    /* SE IMPRIME EL VALOR DE I+3 PARA DEMOSTRAR QUE I YA FUE CONVERTIDO A UN ENTERO. */

    printf("\nIngrese una cadena de caracteres: ");
    gets(cad0);
    d = atof(cad0);
    /* LA FUNCION ATOF CONVIERTE UNA CADENA DE CARACTERES QUE CONTIENE NUMEROS
    REALES A UN VALOR DE TIPO DOUBLE. SI LA CADENA COMIENZA CON OTRO CARACTER
    O NO CONTIENE NUMEROS, RERESA 0 O EL VALOR QUEDA INDEFINIDO. */
    printf("\n%s \t%.2lf", cad0, d+1.50);

    d = strtod(cad0, &cad1);
    /* LA FUNCION STRTOD CONVIERTE UNA CADENA DE CARACTERES QUE CONTIENE NUMEROS
    REALES A UN VALOR DE TIPO DOUBLE. EL RESTO DE LA CADENA SE ALMACENA EN EL
    SEUNDO ARGUMENTO DE LA FUNCION, &CAD1, UN APUNTADOR DE TIPO CADENA DE
    CARACTERES. SI LA CADENA NO CONTIENE NUMEROS O COMIENZA CON OTRO CARACTER,
    RERESA 0 O EL VALOR QUEDA INDEFINIDO. */
    printf("\n%s \t%.2lf", cad0, d+1.50);
    puts(cad1);

    l = atol(cad0);
    /* LA FUNCION ATOL CONVIERTE UNA CADENA DE CARACTERES QUE CONTIENE NUMEROS A
    UN VALOR DE TIPO LONG. SI LA CADENA NO CONTIENE NUMEROS O COMIENZA CON
    OTRO CARACTER, REGRESA 0 O EL VALOR QUEDA INDEFINIDO. */
    printf("\n%s \t%ld", cad0, 1+10);

    l = strtol(cad0, &cad1, 0);
    /* LA FUNCION STRTOL CONVIERTE UNA CADENA DE CARACTERES QUE CONTIENE NUMEROS A
    UN VALOR DE TIPO LONG. EL RESTO DE LA CADENA SE ALMACENA EN EL OTRO ARGUMENTO
    DE LA FUNCION, &CAD1. EL TERCER ARGUMENTO SE UTILIZA PARA INDICAR QUE LA
    CADENA PUEDE ESTAR EN FORMATO OCTAL, DECIMAL O HEXADECIMAL. SI LA CADENA NO
    CONTIENE NUMEROS O COMIENZA CON OTRO CARACTER, REGRESA 0 O EL VALOR QUEDA
    INDEFINIDO. */
    printf("\n%s \t %ld", cad0, 1+10);
    puts(cad1);
}
